# Lenguaje de la aplicación
language:
  - node_js

node_js:
  - "14.15.0" # Versión de mi contenedor (LTS)

# Acto seguido, instalo el task runner
install:
  - npm install -g gulp
  - npm link gulp

# Mediante el task runner instalo las dependencias y ejecuto los tests
script:
  - gulp install
  - gulp test
