# Lenguaje de la aplicación
language:
  - node_js

node_js:
  - "14.13.0" # Versión de mi PC

env:
  - NODE_PATH=/root/.nvm/versions/node/v14.13.0/lib/node_modules

# Acto seguido, instalo el task runner
before_install:
  - npm install -g gulp gulp-mocha gulp-run

# Mediante el task runner instalo las dependencias
install:
  - gulp install

# Mediante el task runner ejecuto los tests
script:
  - gulp test
