# Lenguaje de la aplicación
language:
  - node_js

node_js:
  - 4.2.3

# Acto seguido, instalo el task runner
install:
  - npm install gulp

# Mediante el task runner instalo las dependencias y ejecuto los tests
script:
  - gulp install
  - gulp test
