# Lenguaje de la aplicación
language:
  - node_js

# Distintas versiones del lenguaje sobre las que voy a ejecutar los tests
node.js:
  - 7.2.4

# Instalo las dependencias de la aplicación mediante npm, instalo el task runner y
# mediante él ejecuto los tests
build:
  pre_ci_boot:
    image_name: davidspace/aroundtheworld
    image_tag: latest
    pull: true
    env: FOO=bar
    options: "-e HOME=/root"

  ci:
    - docker run -t -v `pwd`:/test davidspace/aroundtheworld
