# Lenguaje de la aplicación
language:
  - node_js

# Distintas versiones del lenguaje sobre las que voy a ejecutar los tests
node.js:
  - 7.2.4

# Instalo las dependencias de la aplicación mediante npm, instalo el task runner y
# mediante él ejecuto los tests
before_install:
  - source ~/.nvm/nvm.sh && nvm install v14.13.0
  - node --version

install:
  - npm install
  - npm install -g gulp-cli

script:
  - gulp test
