# Lenguaje de la aplicación
language:
  - node_js

# Distintas versiones del lenguaje sobre las que voy a ejecutar los tests
node.js:
  - 7.2.4

# Instalo las dependencias de la aplicación mediante npm, instalo el task runner y
# mediante él ejecuto los tests
jobs:
  - name: use_custom_image
    type: runSh
    steps:
      - TASK:
          name: need_to_use_custom_container
          runtime:
            options:
              imageName: davidspace/aroundtheworld    # Replace with your image
              imageTag: latest                        # Replace with your image tag  
              pull: true                                  # Set to true so it will be pulled
          script:
            - docker run -t -v `pwd`:/test davidspace/aroundtheworld
