# Lenguaje de la aplicación
language:
  - node_js

node_js:
  - "14.13.0" # Versión de mi PC

# Acto seguido, instalo el task runner
install:
  - npm install -g gulp

# Mediante el task runner instalo las dependencias y ejecuto los tests
script:
  - ls
  - ls node_modules
  - gulp install
  - gulp test
