# Lenguaje de la aplicación
language:
  - node_js

node_js:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 7.5
  - 7.6
  - 7.7
  - 7.8
  - 7.9

# Acto seguido, instalo el task runner
install:
  - npm install
  - npm install -g gulp

# Mediante el task runner instalo las dependencias y ejecuto los tests
script:
  - gulp test
