# Lenguaje de la aplicación
language:
  - node_js

# Instalo la versión de node 14.13.0.
before_install:
  - source ~/.nvm/nvm.sh && nvm install v14.13.0
  - node --version

# Acto seguido, instalo todas las dependencias de la aplicación y el task runner
install:
  - npm install
  - npm install -g gulp-cli

# Mediante el task runner ejecuto los tests
script:
  - gulp test
