# Lenguaje de la aplicación
language:
  - node_js

node_js:
  - "14.13.0" # Versión de mi PC

# Acto seguido, instalo el task runner
before_install:
  - npm install -g gulp
  - cat $NODE_PATH

# Mediante el task runner instalo las dependencias
install:
  - gulp install

# Mediante el task runner ejecuto los tests
script:
  - gulp test
