# Lenguaje de la aplicación
language: node_js

# Versiones utilizadas del lenguaje
node_js: "14.13.0" # Versión de mi PC

# Indico en la variable de entorno NODE_PATH la ruta donde se localizan los módulos instalados de manera global
env: eval NODE_PATH="/root/.nvm/versions/node/${SHIPPABLE_NODE_VERSION}/lib/node_modules"

# Acto seguido, instalo el task runner junto a los paquetes que necesita para su funcionamiento
before_install: npm install -g gulp gulp-mocha gulp-run

# Mediante el task runner instalo todas las dependencias del proyecto
install: gulp install

# Mediante el task runner ejecuto los tests
script: gulp test
