# Lenguaje de la aplicación
language: node_js

# Versiones utilizadas del lenguaje
node_js:
  - "12.19.0" # Versión LTS
  - "14.13.0" # Versión de mi PC
  - "14.15.0" # Versión de mi contenedor (LTS)
  - "15.1.0" # Versión más reciente

build:
# Acto seguido, instalo el task runner junto a los paquetes que necesita para su funcionamiento
  ci: 
    - npm install -g gulp gulp-mocha gulp-run
    - export NODE_PATH="/root/.nvm/versions/node/${SHIPPABLE_NODE_VERSION}/lib/node_modules"

# Mediante el task runner instalo todas las dependencias del proyecto
    - gulp install

# Mediante el task runner ejecuto los tests
    - gulp test
