# Lenguaje de la aplicación
language:
  - node_js

node_js:
  - "8" # Versión más antigua que funciona
  - "12.19.0" # Versión LTS
  - "14.13.0" # Versión de mi PC
  - "14.15.0" # Versión de mi contenedor (LTS)
  - "15.1.0" # Versión más reciente

# Acto seguido, instalo el task runner
install:
  - npm install
  - npm install -g gulp

# Mediante el task runner instalo las dependencias y ejecuto los tests
script:
  - gulp test
